version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: 'project.log'

loggers:
  dwlabRuntimeEnvironment:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no
    
  objectHandler:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no

  settingsFile:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, file_handler]
