#!/bin/bash
# Install dwlabbasicpy
/opt/dwlab/dwlab-basicservices/setup/bin/01_modify_etc_bash_bashrc.sh
if [ $? != 0 ]
then
  echo "DW-Lab: $thisScript:"
  echo "DW-Lab: Error during modification of /etc/bash.bashrc"
  exit 8
fi

/opt/dwlab/dwlab-basicservices/setup/bin/02_implement_basicservices.sh
if [ $? != 0 ]
then
  echo "DW-Lab: $thisScript:"
  echo "DW-Lab: Error during implementation of dwlab-basicservices"
  exit 8
fi
